import React, { createContext, useContext, useState } from "react";

const LanguageContext = createContext();

export const translations = {
  es: {
    nav: {
      inicio: "Inicio",
      servicios: "Servicios",
      nosotros: "Nosotros",
      proceso: "Proceso",
      contacto: "Contacto",
    },
    hero: {
      badge: "Tu socio estratégico en tecnología",
      title1: "Tu soporte técnico",
      title2: "de confianza",
      title3: "para que nunca pierdas el ritmo",
      subtitle: "Transformación digital, desarrollo de software y soporte técnico especializado para empresas que buscan eficiencia y crecimiento.",
      cta: "Solicitar Servicios",
      ctaSecondary: "Ver Servicios",
      badge1: "Soporte 24/7",
      badge2: "Respuesta rápida",
      badge3: "Remoto y presencial",
    },
    services: {
      title: "Nuestros",
      titleHighlight: "Servicios",
      subtitle: "Soluciones integrales de tecnología para llevar tu empresa hacia la transformación digital",
      verDetalles: "Ver detalles",
      verMenos: "Ver menos",
      queIncluye: "¿Qué incluye?",
      modalidad: "Modalidad",
      paraQuien: "¿Para quién es ideal?",
    },
    about: {
      title: "Bienvenidos a la",
      titleHighlight: "evolución digital",
      p1: "En PULSO Information Technology, C.A., nos convertimos en tu socio estratégico ideal para llevar a tu empresa hacia la transformación digital.",
      p2: "Garantizamos la continuidad operativa y la máxima eficiencia en los sectores comercial e industrial a través de soluciones de alto nivel. Diseñamos soluciones con precisión para responder a tus necesidades actuales.",
      mision: "Misión",
      misionText: "Proveer soluciones integrales e innovadoras en tecnologías de la información y transformación digital, garantizando la continuidad operativa y la eficiencia de nuestros clientes en los sectores comercial e industrial. Nos comprometemos a entregar soporte técnico especializado, desarrollo de software a medida, diseño de redes y consultoría tecnológica bajo los más altos estándares, optimizando la infraestructura digital para impulsar el crecimiento sostenible de los negocios.",
      vision: "Visión",
      visionText: "Consolidarnos para el año 2031 como la empresa líder y el referente principal en servicios de infraestructura tecnológica y desarrollo de software en la región. Aspiramos a ser reconocidos por nuestra excelencia técnica, la confiabilidad de nuestras soluciones digitales y nuestra capacidad para transformar empresas, convirtiéndonos en el socio estratégico indispensable que impulse la evolución digital y tecnológica de las organizaciones.",
      stat1: "Compromiso",
      stat2: "Comercial e Industrial",
      stat3: "& Presencial",
      stat4: "Nivel de servicio",
    },
    process: {
      title: "Nuestro",
      titleHighlight: "Proceso",
      subtitle: "Un camino claro y transparente desde el primer contacto hasta la solución",
      steps: [
        { title: "Contacto inicial", description: "Nos cuentas tu necesidad o problema. Evaluamos tu caso sin compromiso." },
        { title: "Diagnóstico", description: "Analizamos tu infraestructura, procesos o requerimientos a fondo." },
        { title: "Implementación", description: "Desarrollamos e implementamos la solución con precisión y eficiencia." },
        { title: "Soporte continuo", description: "Te acompañamos post-implementación con mantenimiento y soporte." },
      ],
    },
    whyUs: {
      title: "¿Por qué",
      titleHighlight: "elegirnos",
      titleEnd: "?",
      subtitle: "Combinamos experiencia, tecnología y compromiso para ofrecer resultados excepcionales",
      reasons: [
        { title: "Experiencia comprobada", description: "Profesionales certificados en tecnologías de vanguardia para garantizar resultados." },
        { title: "Respuesta inmediata", description: "Atención rápida y eficiente para minimizar tiempos de inactividad en tu operación." },
        { title: "Soluciones a medida", description: "Cada proyecto es único. Diseñamos soluciones adaptadas a tus necesidades específicas." },
        { title: "Socio estratégico", description: "No solo resolvemos problemas: te acompañamos en tu crecimiento y transformación digital." },
        { title: "Tecnología de punta", description: "Trabajamos con las plataformas y herramientas más avanzadas del mercado." },
        { title: "Seguridad garantizada", description: "Protegemos tus datos y sistemas con los más altos estándares de seguridad informática." },
      ],
    },
    contact: {
      title: "Hablemos de tu",
      titleHighlight: "proyecto",
      subtitle: "Cuéntanos qué necesitas y te responderemos con una propuesta personalizada a la brevedad.",
      location: "Venezuela — Remoto y presencial",
      name: "Nombre completo",
      namePlaceholder: "Tu nombre",
      email: "Email",
      phone: "Teléfono",
      service: "Servicio de interés",
      servicePlaceholder: "Selecciona un servicio",
      message: "Mensaje",
      messagePlaceholder: "Cuéntanos sobre tu proyecto o necesidad...",
      send: "Enviar Solicitud",
      sending: "Enviando...",
      successTitle: "¡Mensaje enviado!",
      successDesc: "Nos pondremos en contacto contigo pronto.",
      errorTitle: "Error",
      errorDesc: "Hubo un problema al enviar. Intenta de nuevo.",
      services: ["Soporte Técnico", "Desarrollo Web", "Automatizaciones", "Reparación y Diagnóstico", "Mantenimiento Preventivo", "Plan de Soporte Remoto Mensual", "Asesoría Tecnológica", "Desarrollo de API REST", "Configuración de Red Básica", "Otro"],
    },
    footer: {
      tagline: "Tu soporte de confianza para que nunca pierdas el ritmo. Transformación digital para empresas.",
      navigation: "Navegación",
      services: "Servicios",
      contact: "Contacto",
      rights: "Todos los derechos reservados.",
      slogan: "Diseñamos soluciones con precisión",
      links: [
        { label: "Inicio", href: "#inicio" },
        { label: "Servicios", href: "#servicios" },
        { label: "Nosotros", href: "#nosotros" },
        { label: "Proceso", href: "#proceso" },
        { label: "Contacto", href: "#contacto" },
      ],
      serviceLinks: ["Soporte Técnico", "Desarrollo Web", "Automatizaciones", "Reparación y Diagnóstico", "Mantenimiento Preventivo", "Plan de Soporte Remoto Mensual", "Asesoría Tecnológica", "Desarrollo de API REST", "Configuración de Red Básica"],
    },
  },
  en: {
    nav: {
      inicio: "Home",
      servicios: "Services",
      nosotros: "About",
      proceso: "Process",
      contacto: "Contact",
    },
    hero: {
      badge: "Your strategic technology partner",
      title1: "Your trusted",
      title2: "tech support",
      title3: "so you never lose your rhythm",
      subtitle: "Digital transformation, software development and specialized technical support for companies seeking efficiency and growth.",
      cta: "Request Services",
      ctaSecondary: "View Services",
      badge1: "24/7 Support",
      badge2: "Fast response",
      badge3: "Remote & on-site",
    },
    services: {
      title: "Our",
      titleHighlight: "Services",
      subtitle: "Comprehensive technology solutions to drive your company toward digital transformation",
      verDetalles: "View details",
      verMenos: "View less",
      queIncluye: "What's included?",
      modalidad: "Mode",
      paraQuien: "Who is it ideal for?",
    },
    about: {
      title: "Welcome to the",
      titleHighlight: "digital evolution",
      p1: "At PULSO Information Technology, C.A., we become your ideal strategic partner to lead your company toward digital transformation.",
      p2: "We guarantee operational continuity and maximum efficiency in the commercial and industrial sectors through high-level solutions. We design solutions with precision to respond to your current needs.",
      mision: "Mission",
      misionText: "To provide comprehensive and innovative solutions in information technology and digital transformation, guaranteeing the operational continuity and efficiency of our clients in the commercial and industrial sectors. We are committed to delivering specialized technical support, custom software development, network design and technology consulting under the highest standards, optimizing digital infrastructure to drive sustainable business growth.",
      vision: "Vision",
      visionText: "To consolidate by 2031 as the leading company and main reference in technological infrastructure services and software development in the region. We aspire to be recognized for our technical excellence, the reliability of our digital solutions and our ability to transform companies, becoming the indispensable strategic partner that drives the digital and technological evolution of organizations.",
      stat1: "Commitment",
      stat2: "Commercial & Industrial",
      stat3: "& On-site",
      stat4: "Service level",
    },
    process: {
      title: "Our",
      titleHighlight: "Process",
      subtitle: "A clear and transparent path from first contact to solution",
      steps: [
        { title: "Initial contact", description: "Tell us your need or problem. We evaluate your case with no commitment." },
        { title: "Diagnosis", description: "We thoroughly analyze your infrastructure, processes or requirements." },
        { title: "Implementation", description: "We develop and implement the solution with precision and efficiency." },
        { title: "Ongoing support", description: "We accompany you post-implementation with maintenance and support." },
      ],
    },
    whyUs: {
      title: "Why",
      titleHighlight: "choose us",
      titleEnd: "?",
      subtitle: "We combine experience, technology and commitment to deliver exceptional results",
      reasons: [
        { title: "Proven experience", description: "Certified professionals in cutting-edge technologies to guarantee results." },
        { title: "Immediate response", description: "Fast and efficient support to minimize downtime in your operations." },
        { title: "Tailored solutions", description: "Every project is unique. We design solutions adapted to your specific needs." },
        { title: "Strategic partner", description: "We don't just solve problems: we accompany you in your growth and digital transformation." },
        { title: "Cutting-edge technology", description: "We work with the most advanced platforms and tools on the market." },
        { title: "Guaranteed security", description: "We protect your data and systems with the highest information security standards." },
      ],
    },
    contact: {
      title: "Let's talk about your",
      titleHighlight: "project",
      subtitle: "Tell us what you need and we'll respond with a personalized proposal as soon as possible.",
      location: "Venezuela — Remote & on-site",
      name: "Full name",
      namePlaceholder: "Your name",
      email: "Email",
      phone: "Phone",
      service: "Service of interest",
      servicePlaceholder: "Select a service",
      message: "Message",
      messagePlaceholder: "Tell us about your project or need...",
      send: "Send Request",
      sending: "Sending...",
      successTitle: "Message sent!",
      successDesc: "We will get in touch with you soon.",
      errorTitle: "Error",
      errorDesc: "There was a problem sending. Please try again.",
      services: ["Technical Support", "Web Development", "Automations", "Repair & Diagnosis", "Preventive Maintenance", "Monthly Remote Support Plan", "Technology Consulting", "REST API Development", "Basic Network Setup", "Other"],
    },
    footer: {
      tagline: "Your trusted support so you never lose your rhythm. Digital transformation for companies.",
      navigation: "Navigation",
      services: "Services",
      contact: "Contact",
      rights: "All rights reserved.",
      slogan: "We design solutions with precision",
      links: [
        { label: "Home", href: "#inicio" },
        { label: "Services", href: "#servicios" },
        { label: "About", href: "#nosotros" },
        { label: "Process", href: "#proceso" },
        { label: "Contact", href: "#contacto" },
      ],
      serviceLinks: ["Technical Support", "Web Development", "Automations", "Repair & Diagnosis", "Preventive Maintenance", "Monthly Remote Support Plan", "Technology Consulting", "REST API Development", "Basic Network Setup"],
    },
  },
};

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState("es");
  const t = translations[lang];
  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLang() {
  return useContext(LanguageContext);
}