import React, { createContext, useContext, useState } from "react";

const LanguageContext = createContext();

export const translations = {
  es: {
    nav: {
      inicio: "Inicio",
      servicios: "Servicios",
      nosotros: "Nosotros",
      proceso: "Proceso",
      contacto: "Contacto",
    },
    hero: {
      badge: "Tu socio estratégico en tecnología",
      title1: "Tu soporte técnico",
      title2: "de confianza",
      title3: "para que nunca pierdas el ritmo",
      subtitle: "Transformación digital, desarrollo de software y soporte técnico especializado para empresas que buscan eficiencia y crecimiento.",
      cta: "Solicitar Servicios",
      ctaSecondary: "Ver Servicios",
      badge1: "Soporte 24/7",
      badge2: "Respuesta rápida",
      badge3: "Remoto y presencial",
    },
    services: {
      title: "Nuestros",
      titleHighlight: "Servicios",
      subtitle: "Soluciones integrales de tecnología para llevar tu empresa hacia la transformación digital",
      verDetalles: "Ver detalles",
      verMenos: "Ver menos",
      queIncluye: "¿Qué incluye?",
      modalidad: "Modalidad",
      paraQuien: "¿Para quién es ideal?",
      items: [
        {
          id: "soporte",
          title: "Soporte Técnico",
          subtitle: "Especializado y preventivo",
          description: "Garantizamos la continuidad operativa con soporte técnico de alto nivel para los sectores comercial e industrial.",
          features: ["Soporte técnico especializado y mantenimiento preventivo", "Desarrollo de software a medida y APIs", "Diseño de redes y consultoría tecnológica"],
        },
        {
          id: "web",
          title: "Desarrollo Web",
          subtitle: "Sitios profesionales",
          description: "Creamos sitios web responsivos, optimizados para SEO y velocidad, con integración de e-commerce y pasarelas de pago.",
          features: ["Diseño UI/UX personalizado", "Desarrollo de sitio web responsivo", "Integración de CMS (WordPress, etc.)", "Optimización SEO y de velocidad", "Integración de e-commerce y pasarelas de pago", "Autenticación segura", "Despliegue en la nube y mantenimiento"],
          ideal: ["Emprendedores y startups", "Empresas que buscan presencia digital", "Negocios e-commerce que quieren vender más", "Creadores de contenido y blogs", "Cualquier negocio con necesidad de crecimiento online"],
        },
        {
          id: "automatizaciones",
          title: "Automatizaciones",
          subtitle: "Optimiza tu negocio",
          description: "Implementamos flujos de trabajo automatizados con tecnologías líderes como N8N, Microsoft Power Platform y agentes de IA.",
          features: ["Flujos de trabajo automatizados (e-commerce, CRM)", "Workflows de procesos empresariales end-to-end", "Desarrollo robusto en N8N (soluciones Open-Source)", "Desarrollo especializado en tecnologías Microsoft Power Platform: PowerBI, PowerApps, PowerAutomate", "Integraciones avanzadas con Agentes de IA conversacionales y de datos"],
          modal: "Remoto (implementación y soporte)",
          ideal: ["Dueños de negocios que buscan eficiencia y reducción de costos", "Gerentes de operaciones y logística con cuellos de botella", "Startups y empresas en crecimiento que escalan rápidamente", "Profesionales de marketing y ventas que desean leads más cualificados"],
        },
        {
          id: "reparacion",
          title: "Reparación y Diagnóstico",
          subtitle: "Presencial",
          description: "Evaluación completa de equipos, limpieza de hardware, resolución de errores de software e instalación de programas.",
          features: ["Evaluación completa del equipo", "Limpieza básica de hardware", "Resolución de errores de software", "Instalación de programas básicos"],
          modal: "Presencial (en domicilio o empresa)",
          ideal: ["Usuarios con equipos lentos", "Fallos recurrentes", "Pantallas congeladas", "Software que no inicia"],
        },
        {
          id: "mantenimiento",
          title: "Mantenimiento Preventivo",
          subtitle: "Presencial",
          description: "Limpieza y optimización profunda del sistema para extender la vida útil de tu equipo y mantenerlo libre de virus.",
          features: ["Limpieza profunda del sistema operativo", "Eliminación de archivos basura y cachés", "Actualización y optimización de antivirus"],
          modal: "Presencial (en domicilio o empresa)",
          ideal: ["Para quienes desean extender la vida útil de su PC", "Usuarios que notan lentitud y quieren recuperar velocidad", "Personas que buscan un rendimiento óptimo y sin virus"],
        },
        {
          id: "soporte-remoto",
          title: "Plan de Soporte Remoto Mensual",
          subtitle: "100% remoto",
          description: "Hasta 3 sesiones de soporte remoto al mes con resolución de problemas comunes, optimización y soporte multi-dispositivo.",
          features: ["Hasta 3 sesiones de soporte remoto al mes", "Resolución de problemas comunes: lentitud, errores, actualizaciones", "Optimización y mantenimiento del sistema", "Soporte multi-dispositivo"],
          modal: "Soporte 100% remoto (vía control remoto)",
          ideal: ["Negocios con 1 a 5 equipos", "Empresas sin personal técnico interno", "Usuarios que necesitan soporte rápido y flexible", "Quienes buscan mantenimiento preventivo y correctivo de bajo costo"],
        },
        {
          id: "asesoria",
          title: "Asesoría Tecnológica",
          subtitle: "Presencial o remoto",
          description: "Recomendaciones personalizadas de compra, configuración avanzada de sistemas y asesoría sobre uso seguro de la tecnología.",
          features: ["Recomendaciones de compra personalizadas", "Configuración avanzada de sistemas y dispositivos", "Asesoría especializada sobre uso seguro de tecnología"],
          modal: "Presencial o remoto (a elección)",
          ideal: ["Personas que están por adquirir nuevos equipos y desean optimizar su inversión", "Usuarios que buscan mejorar y proteger su entorno digital", "Emprendedores que necesitan optimizar sus herramientas"],
        },
        {
          id: "api-rest",
          title: "Desarrollo de API REST",
          subtitle: "Personalizadas",
          description: "Diseño y arquitectura de APIs robustas con autenticación OAuth2/JWT, documentación Swagger y despliegue en la nube.",
          features: ["Diseño y arquitectura de API REST", "Integración de bases de datos segura", "Documentación interactiva (Swagger)", "Pruebas de rendimiento y seguridad", "Autenticación (OAuth2, JWT)", "Despliegue en la nube", "Escalabilidad y mantenimiento continuo"],
          ideal: ["Startups que necesitan un backend robusto", "Empresas integrando múltiples sistemas", "Desarrolladores que buscan un API de terceros", "E-commerce y aplicaciones móviles", "Negocios con necesidad de automatización"],
        },
        {
          id: "red",
          title: "Configuración de Red Básica",
          subtitle: "Presencial",
          description: "Instalación de router de alto rendimiento, conexión para todos los dispositivos, impresoras compartidas y red local optimizada.",
          features: ["Instalación de routers de alto rendimiento", "Conexión para todos los dispositivos", "Configuración de impresoras compartidas", "Creación y optimización de red local"],
          modal: "Presencial (diseñado para empresas y hogares)",
          ideal: ["Hogares que necesitan cobertura Wi-Fi completa (sin zonas muertas)", "Empresas en general que requieran un trabajo en red eficiente", "Personas que busquen compartir archivos y equipos de forma fácil", "Usuarios que deseen una red más rápida y estable"],
        },
      ],
    },
    about: {
      title: "Bienvenidos a la",
      titleHighlight: "evolución digital",
      p1: "PULSO Information Technology, C.A., nos convertimos en tu socio estratégico ideal para llevar a tu empresa hacia la transformación digital.",
      p2: "Garantizamos la continuidad operativa y la máxima eficiencia en los sectores comercial e industrial a través de soluciones de alto nivel. Diseñamos soluciones con precisión para responder a tus necesidades actuales.",
      mision: "Misión",
      misionText: "Proveer soluciones integrales e innovadoras en tecnologías de la información y transformación digital, garantizando la continuidad operativa y la eficiencia de nuestros clientes en los sectores comercial e industrial. Nos comprometemos a entregar soporte técnico especializado, desarrollo de software a medida, diseño de redes y consultoría tecnológica bajo los más altos estándares, optimizando la infraestructura digital para impulsar el crecimiento sostenible de los negocios.",
      vision: "Visión",
      visionText: "Consolidarnos para el año 2031 como la empresa líder y el referente principal en servicios de infraestructura tecnológica y desarrollo de software en la región. Aspiramos a ser reconocidos por nuestra excelencia técnica, la confiabilidad de nuestras soluciones digitales y nuestra capacidad para transformar empresas, convirtiéndonos en el socio estratégico indispensable que impulse la evolución digital y tecnológica de las organizaciones.",
      stat1: "Compromiso",
      stat2: "Comercial e Industrial",
      stat3: "& Presencial",
      stat4: "Nivel de servicio",
    },
    process: {
      title: "Nuestro",
      titleHighlight: "Proceso",
      subtitle: "Un camino claro y transparente desde el primer contacto hasta la solución",
      steps: [
        { title: "Contacto inicial", description: "Nos cuentas tu necesidad o problema. Evaluamos tu caso sin compromiso." },
        { title: "Diagnóstico", description: "Analizamos tu infraestructura, procesos o requerimientos a fondo." },
        { title: "Implementación", description: "Desarrollamos e implementamos la solución con precisión y eficiencia." },
        { title: "Soporte continuo", description: "Te acompañamos post-implementación con mantenimiento y soporte." },
      ],
    },
    whyUs: {
      title: "¿Por qué",
      titleHighlight: "elegirnos",
      titleEnd: "?",
      subtitle: "Combinamos experiencia, tecnología y compromiso para ofrecer resultados excepcionales",
      reasons: [
        { title: "Experiencia comprobada", description: "Profesionales certificados en tecnologías de vanguardia para garantizar resultados." },
        { title: "Respuesta inmediata", description: "Atención rápida y eficiente para minimizar tiempos de inactividad en tu operación." },
        { title: "Soluciones a medida", description: "Cada proyecto es único. Diseñamos soluciones adaptadas a tus necesidades específicas." },
        { title: "Socio estratégico", description: "No solo resolvemos problemas: te acompañamos en tu crecimiento y transformación digital." },
        { title: "Tecnología de punta", description: "Trabajamos con las plataformas y herramientas más avanzadas del mercado." },
        { title: "Seguridad garantizada", description: "Protegemos tus datos y sistemas con los más altos estándares de seguridad informática." },
      ],
    },
    contact: {
      title: "Hablemos de tu",
      titleHighlight: "proyecto",
      subtitle: "Cuéntanos qué necesitas y te responderemos con una propuesta personalizada a la brevedad.",
      location: "Venezuela — Remoto y presencial",
      name: "Nombre completo",
      namePlaceholder: "Tu nombre",
      email: "Email",
      phone: "Teléfono",
      service: "Servicio de interés",
      servicePlaceholder: "Selecciona un servicio",
      message: "Mensaje",
      messagePlaceholder: "Cuéntanos sobre tu proyecto o necesidad...",
      send: "Enviar Solicitud",
      sending: "Enviando...",
      successTitle: "¡Mensaje enviado!",
      successDesc: "Nos pondremos en contacto contigo pronto.",
      errorTitle: "Error",
      errorDesc: "Hubo un problema al enviar. Intenta de nuevo.",
      services: ["Soporte Técnico", "Desarrollo Web", "Automatizaciones", "Reparación y Diagnóstico", "Mantenimiento Preventivo", "Plan de Soporte Remoto Mensual", "Asesoría Tecnológica", "Desarrollo de API REST", "Configuración de Red Básica", "Otro"],
    },
    footer: {
      tagline: "Tu soporte de confianza para que nunca pierdas el ritmo. Transformación digital para empresas.",
      navigation: "Navegación",
      services: "Servicios",
      contact: "Contacto",
      rights: "Todos los derechos reservados.",
      slogan: "Diseñamos soluciones con precisión",
      links: [
        { label: "Inicio", href: "#inicio" },
        { label: "Servicios", href: "#servicios" },
        { label: "Nosotros", href: "#nosotros" },
        { label: "Proceso", href: "#proceso" },
        { label: "Contacto", href: "#contacto" },
      ],
      serviceLinks: ["Soporte Técnico", "Desarrollo Web", "Automatizaciones", "Reparación y Diagnóstico", "Mantenimiento Preventivo", "Plan de Soporte Remoto Mensual", "Asesoría Tecnológica", "Desarrollo de API REST", "Configuración de Red Básica"],
    },
  },
  en: {
    nav: {
      inicio: "Home",
      servicios: "Services",
      nosotros: "About",
      proceso: "Process",
      contacto: "Contact",
    },
    hero: {
      badge: "Your strategic technology partner",
      title1: "Your trusted",
      title2: "tech support",
      title3: "so you never lose your rhythm",
      subtitle: "Digital transformation, software development and specialized technical support for companies seeking efficiency and growth.",
      cta: "Request Services",
      ctaSecondary: "View Services",
      badge1: "24/7 Support",
      badge2: "Fast response",
      badge3: "Remote & on-site",
    },
    services: {
      title: "Our",
      titleHighlight: "Services",
      subtitle: "Comprehensive technology solutions to drive your company toward digital transformation",
      verDetalles: "View details",
      verMenos: "View less",
      queIncluye: "What's included?",
      modalidad: "Mode",
      paraQuien: "Who is it ideal for?",
      items: [
        {
          id: "soporte",
          title: "Technical Support",
          subtitle: "Specialized & preventive",
          description: "We guarantee operational continuity with high-level technical support for the commercial and industrial sectors.",
          features: ["Specialized technical support and preventive maintenance", "Custom software development and APIs", "Network design and technology consulting"],
        },
        {
          id: "web",
          title: "Web Development",
          subtitle: "Professional sites",
          description: "We create responsive websites, optimized for SEO and speed, with e-commerce and payment gateway integration.",
          features: ["Custom UI/UX design", "Responsive website development", "CMS integration (WordPress, etc.)", "SEO and speed optimization", "E-commerce and payment gateway integration", "Secure authentication", "Cloud deployment and maintenance"],
          ideal: ["Entrepreneurs and startups", "Companies seeking digital presence", "E-commerce businesses that want to sell more", "Content creators and blogs", "Any business with a need for online growth"],
        },
        {
          id: "automatizaciones",
          title: "Automations",
          subtitle: "Optimize your business",
          description: "We implement automated workflows with leading technologies like N8N, Microsoft Power Platform and AI agents.",
          features: ["Automated workflows (e-commerce, CRM)", "End-to-end business process workflows", "Robust N8N development (Open-Source solutions)", "Specialized development in Microsoft Power Platform technologies: PowerBI, PowerApps, PowerAutomate", "Advanced integrations with conversational and data AI Agents"],
          modal: "Remote (implementation and support)",
          ideal: ["Business owners seeking efficiency and cost reduction", "Operations and logistics managers with bottlenecks", "Startups and growing companies that scale rapidly", "Marketing and sales professionals who want more qualified leads"],
        },
        {
          id: "reparacion",
          title: "Repair & Diagnosis",
          subtitle: "On-site",
          description: "Complete equipment evaluation, hardware cleaning, software error resolution and program installation.",
          features: ["Complete equipment evaluation", "Basic hardware cleaning", "Software error resolution", "Basic program installation"],
          modal: "On-site (at home or business)",
          ideal: ["Users with slow equipment", "Recurring failures", "Frozen screens", "Software that won't start"],
        },
        {
          id: "mantenimiento",
          title: "Preventive Maintenance",
          subtitle: "On-site",
          description: "Deep system cleaning and optimization to extend your equipment's lifespan and keep it virus-free.",
          features: ["Deep operating system cleaning", "Junk file and cache removal", "Antivirus update and optimization"],
          modal: "On-site (at home or business)",
          ideal: ["For those who want to extend their PC's lifespan", "Users noticing slowdowns who want to recover speed", "People looking for optimal, virus-free performance"],
        },
        {
          id: "soporte-remoto",
          title: "Monthly Remote Support Plan",
          subtitle: "100% remote",
          description: "Up to 3 remote support sessions per month with common issue resolution, optimization and multi-device support.",
          features: ["Up to 3 remote support sessions per month", "Common issue resolution: slowdowns, errors, updates", "System optimization and maintenance", "Multi-device support"],
          modal: "100% remote support (via remote control)",
          ideal: ["Businesses with 1 to 5 devices", "Companies without internal technical staff", "Users who need fast and flexible support", "Those seeking low-cost preventive and corrective maintenance"],
        },
        {
          id: "asesoria",
          title: "Technology Consulting",
          subtitle: "On-site or remote",
          description: "Personalized purchase recommendations, advanced system configuration and advice on safe technology use.",
          features: ["Personalized purchase recommendations", "Advanced system and device configuration", "Specialized advice on safe technology use"],
          modal: "On-site or remote (your choice)",
          ideal: ["People who are about to acquire new equipment and wish to optimize their investment", "Users looking to improve and protect their digital environment", "Entrepreneurs who need to optimize their tools"],
        },
        {
          id: "api-rest",
          title: "REST API Development",
          subtitle: "Custom",
          description: "Robust API design and architecture with OAuth2/JWT authentication, Swagger documentation and cloud deployment.",
          features: ["REST API design and architecture", "Secure database integration", "Interactive documentation (Swagger)", "Performance and security testing", "Authentication (OAuth2, JWT)", "Cloud deployment", "Scalability and ongoing maintenance"],
          ideal: ["Startups needing a robust backend", "Companies integrating multiple systems", "Developers looking for a third-party API", "E-commerce and mobile applications", "Businesses with automation needs"],
        },
        {
          id: "red",
          title: "Basic Network Setup",
          subtitle: "On-site",
          description: "High-performance router installation, connection for all devices, shared printers and optimized local network.",
          features: ["Installation of high-performance routers", "Connection for all devices", "Shared printer configuration", "Local network creation and optimization"],
          modal: "On-site (designed for businesses and homes)",
          ideal: ["Homes needing complete Wi-Fi coverage (no dead zones)", "Companies in general that require efficient networked work", "People looking to share files and devices easily", "Users wanting a faster and more stable network"],
        },
      ],
    },
    about: {
      title: "Welcome to the",
      titleHighlight: "digital evolution",
      p1: "PULSO Information Technology, C.A., we become your ideal strategic partner to lead your company toward digital transformation.",
      p2: "We guarantee operational continuity and maximum efficiency in the commercial and industrial sectors through high-level solutions. We design solutions with precision to respond to your current needs.",
      mision: "Mission",
      misionText: "To provide comprehensive and innovative solutions in information technology and digital transformation, guaranteeing the operational continuity and efficiency of our clients in the commercial and industrial sectors. We are committed to delivering specialized technical support, custom software development, network design and technology consulting under the highest standards, optimizing digital infrastructure to drive sustainable business growth.",
      vision: "Vision",
      visionText: "To consolidate by 2031 as the leading company and main reference in technological infrastructure services and software development in the region. We aspire to be recognized for our technical excellence, the reliability of our digital solutions and our ability to transform companies, becoming the indispensable strategic partner that drives the digital and technological evolution of organizations.",
      stat1: "Commitment",
      stat2: "Commercial & Industrial",
      stat3: "& On-site",
      stat4: "Service level",
    },
    process: {
      title: "Our",
      titleHighlight: "Process",
      subtitle: "A clear and transparent path from first contact to solution",
      steps: [
        { title: "Initial contact", description: "Tell us your need or problem. We evaluate your case with no commitment." },
        { title: "Diagnosis", description: "We thoroughly analyze your infrastructure, processes or requirements." },
        { title: "Implementation", description: "We develop and implement the solution with precision and efficiency." },
        { title: "Ongoing support", description: "We accompany you post-implementation with maintenance and support." },
      ],
    },
    whyUs: {
      title: "Why",
      titleHighlight: "choose us",
      titleEnd: "?",
      subtitle: "We combine experience, technology and commitment to deliver exceptional results",
      reasons: [
        { title: "Proven experience", description: "Certified professionals in cutting-edge technologies to guarantee results." },
        { title: "Immediate response", description: "Fast and efficient support to minimize downtime in your operations." },
        { title: "Tailored solutions", description: "Every project is unique. We design solutions adapted to your specific needs." },
        { title: "Strategic partner", description: "We don't just solve problems: we accompany you in your growth and digital transformation." },
        { title: "Cutting-edge technology", description: "We work with the most advanced platforms and tools on the market." },
        { title: "Guaranteed security", description: "We protect your data and systems with the highest information security standards." },
      ],
    },
    contact: {
      title: "Let's talk about your",
      titleHighlight: "project",
      subtitle: "Tell us what you need and we'll respond with a personalized proposal as soon as possible.",
      location: "Venezuela — Remote & on-site",
      name: "Full name",
      namePlaceholder: "Your name",
      email: "Email",
      phone: "Phone",
      service: "Service of interest",
      servicePlaceholder: "Select a service",
      message: "Message",
      messagePlaceholder: "Tell us about your project or need...",
      send: "Send Request",
      sending: "Sending...",
      successTitle: "Message sent!",
      successDesc: "We will get in touch with you soon.",
      errorTitle: "Error",
      errorDesc: "There was a problem sending. Please try again.",
      services: ["Technical Support", "Web Development", "Automations", "Repair & Diagnosis", "Preventive Maintenance", "Monthly Remote Support Plan", "Technology Consulting", "REST API Development", "Basic Network Setup", "Other"],
    },
    footer: {
      tagline: "Your trusted support so you never lose your rhythm. Digital transformation for companies.",
      navigation: "Navigation",
      services: "Services",
      contact: "Contact",
      rights: "All rights reserved.",
      slogan: "We design solutions with precision",
      links: [
        { label: "Home", href: "#inicio" },
        { label: "Services", href: "#servicios" },
        { label: "About", href: "#nosotros" },
        { label: "Process", href: "#proceso" },
        { label: "Contact", href: "#contacto" },
      ],
      serviceLinks: ["Technical Support", "Web Development", "Automations", "Repair & Diagnosis", "Preventive Maintenance", "Monthly Remote Support Plan", "Technology Consulting", "REST API Development", "Basic Network Setup"],
    },
  },
};

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState("es");
  const t = translations[lang];
  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLang() {
  return useContext(LanguageContext);
}